---
services:
  init-volume:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - data:/opt/aptos
    command: ${NETWORK}
volumes:
  data:
    name: fullnode_data_${NETWORK}
...

