---
version: '3.8'

services:
  init-volume:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - aptos_data:/opt/aptos
    command: ${NETWORK}

volumes:
  aptos_data:
    name: ${NETWORK}_fullnode_data
...

