---
jobs:
  cache-warm:
    name: 'Cache warming'
    runs-on: 'ubuntu-latest'
    steps:
    - uses: 'actions/checkout@v4'
    - name: 'Warm pre-commit cache'
      uses: './.github/workflows/pre-commit.yaml'
name: 'cache-warm'
'on':
  push:
    branches:
    - 'main'
    paths:
    - 'cfg/pre-commit/**'
    - '.github/workflows/pre-commit.yaml'
    - '.github/workflows/cache-warm.yaml'
permissions:
  contents: 'read'
...

