---
jobs:
  codeowners:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: 'actions/checkout@v4'
    - uses: 'mszostok/codeowners-validator@v0.7.4'
      with:
        experimental_checks: 'avoid-shadowing,notowned'
        github_access_token: '${{ secrets.CODEOWNERS_VALIDATOR_GITHUB_TOKEN }}'
        repository_path: '.github/'
name: 'Verify codeowners'
'on':
  merge_group: null
  pull_request: null
  workflow_dispatch: null
...
