---
jobs:
  approval:
    # Only require manual approval via the `pull-request` environment outside
    # of a merge queue.
    environment: |
      ${{ github.event_name != 'merge_group' && 'pull-request' || '' }}
    name: 'Approval'
    runs-on: 'ubuntu-latest'
    steps:
    - run: 'echo "Workflow approved"'
  pre-commit:
    needs:
    - 'approval'
    uses: './.github/workflows/pre-commit.yaml'
name: 'Housekeeping'
'on':
  merge_group: null
  pull_request: null
...
