---
jobs:
  move-tests:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: 'actions/checkout@v4'
    # yamllint disable-line rule:line-length
    - uses: 'aptos-labs/aptos-core/.github/actions/get-latest-cli@aptos-framework-v1.27.0'
      with:
        destination_directory: '/usr/local/bin'
    - name: 'Find and test Move packages'
      # Find all Move packages and run tests in each directory, exiting on
      # any failure.
      # yamllint disable-line rule:indentation
      run: |
        set -e
        find . -name "Move.toml" | while read -r toml; do
          dir=$(dirname "$toml")
          echo "Testing package in directory: $dir"
          if ! aptos move test --dev --package-dir "$dir"; then
            echo "Test failed in directory: $dir"
            exit 1
          fi
        done
# yamllint enable-line rule:indentation
name: 'move-tests'
'on':
  merge_group: null
  pull_request: null
  workflow_dispatch: null
...
