---
env:
  PRE_COMMIT_VERSION: '4.2.0'
  PYTHON_VERSION: '3.13'
jobs:
  stub:
    name: 'pre-commit'
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        cache: 'pip'
        python-version: '${{ env.PYTHON_VERSION }}'
    - run: 'pip install pre-commit==${{ env.PRE_COMMIT_VERSION }}'
    - uses: actions/cache@v3
      with:
        path: ~/.cache/pre-commit
        key: ${{ runner.os }}-python-${{ env.PYTHON_VERSION }}-precommit-${{ env.PRE_COMMIT_VERSION }}-${{ hashFiles('cfg/pre-commit/yamllint.yaml') }}
    - run: 'pre-commit install-hooks -c cfg/pre-commit/yamllint.yaml'
    - run: 'pre-commit run --all-files --show-diff-on-failure --color=always -c cfg/pre-commit/yamllint.yaml'
name: 'pre-commit'
'on':
  merge_group: null
  pull_request: null
...
