---
jobs:
  stub:
    name: 'pre-commit'
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        cache: 'pip'
    - run: 'pip install pre-commit'
name: 'pre-commit'
'on':
  merge_group: null
  pull_request: null
...
