---
env:
  AWS_ACCOUNT_ID: '123456'
  AWS_REGION: 'us-west-2'
  BUILD_CONTEXT: 'aptos-node/fullnode-init'
  ECR_REPO: 'aptos-node/fullnode-init'
  GIT_TAG_PREFIX: 'fullnode-init'
jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: 'actions/checkout@v4'
    - uses: 'docker/setup-buildx-action@v3'
    - uses: 'docker/metadata-action@v5'
      with:
        images: '${{ env.ECR_REPO }}'
        tags: |
          type=match,pattern=${{ env.GIT_TAG_PREFIX }}-v(.*),group=1
          type=raw,value=latest,enable={{is_default_branch}}
    - id: 'build'
      uses: 'docker/build-push-action@v6'
      with:
        push: 'false'
        context: '${{ env.BUILD_CONTEXT }}'
        load: 'true'
    - env:
        AWS_ACCOUNT_ID: '${{ env.AWS_ACCOUNT_ID }}'
        AWS_REGION: '${{ env.AWS_REGION }}'
        ECR_REPO: '${{ env.ECR_REPO }}'
        IMAGE_ID: '${{ steps.build.outputs.imageid }}'
        TAGS: '${{ steps.meta.outputs.tags }}'
      run: 'sh ${{ github.workspace }}/.github/workflows/sh/push-to-aws-ecr.sh'
name: 'Push fullnode init image to ECR'
'on':
  push:
    tags:
    - 'fullnode-init-v*'