# cspell:word amannn
---
jobs:
  semantic-pr:
    name: 'Semantic PR'
    runs-on: 'ubuntu-latest'
    steps:
    - env:
        GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      # Assume success in a merge group by skipping the action, which can't
      # access PR titles inside a merge group.
      if: |
        github.event_name != 'merge_group'
      uses: 'amannn/action-semantic-pull-request@v5'
      with:
        requireScope: true
        scopes: '^ECO-[0-9]+$'
        subjectPattern: '^[A-Z].*$'
        validateSingleCommit: true
        validateSingleCommitMatchesPrTitle: true
'on':
  workflow_call: null
permissions:
  contents: 'read'
  pull-requests: 'read'
...
