---
jobs:
  pre-commit:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: './.github/workflows/pre-commit.yaml'
name: 'Warm cache'
'on':
  push:
    branches:
    - 'main'
    paths:
    - 'cfg/pre-commit/**'
    - '.github/workflows/pre-commit.yaml'
    - '.github/workflows/warm-cache.yaml'
permissions:
  contents: 'read'
...

